[package]
name = "rdoist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.12.5", features = ["json"]}
openssl = {features = ["vendored"]}
tokio = {features = ["full"]}
clap = {version = "4.5.8", features = ["derive"]}
home = "0.5.9"
toml = "0.8.14"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
regex = "1.10.5"
